name: DETR
type: det
args:
  backbone: 
    name: resnet50
    args: 
      dilation: True
      position_embedding: sine    #sine, learned
  transformer: 
    args:
      enc_layers: 6
      dec_layers: 6
      dim_feedforward: 2048
      hidden_dim: 256
      dropout: 0.1
      nheads: 8
      num_queries: 100
      pre_norm: True
  matcher:
    set_cost_class: 1
    set_cost_bbox: 5
    set_cost_giou: 2
  aux_loss: False