name: ROI_DySeg
type: seg
args:
  blocks: [1, 2, 3, 2]
  channels: [24, 48, 60]
  conv_r: [4, 2, 2, 2]
  dropout: 0.3
  embed_dim: 96
  embedding_dim: 8
  heads: [1, 2, 4, 4]
  in_channels: 1
  out_channels: 1
  r: [4, 2, 2, 1]