
run:
  work_dir: /data/jayeon/TrainedData/Paper/
  dataset: amos22
  model: detseg
  checkpoint: Pretrain_Test
  device_num: [1]
  num_workers: 8

train:
  resume: False
  batch: 4
  epoch: 1000
  lr: 2e-3
  save_cycle: 200
  warmup: 5

inference:
  epoch: best
  weight_path: train
  direct_path: null

generation:
  epoch: best
  weight_path: train
  direct_path: null