generation:
  direct_path: null
  epoch: best
  weight_path: train
inference:
  direct_path: null
  epoch: best
  weight_path: train
run:
  checkpoint: Dev_SlimUNETR_amos22_lab1_128_01
  device_num: "1"
  generation_mode: false
  inference_mode: false
  loader:
    target_labels:
      - 1
    batch_size: 4
    drop_last: true
    num_workers: 4
    pin_memory: true
    dataset:
      name: amos22
      root: /data/jayeon/dataset/Amos22_RAS/
      scale: 128
    generation:
      test: 1
    train:
      test: 1
    validation:
      test: 1
  model:
    args:
      blocks:
      - 1
      - 2
      - 3
      - 2
      channels:
      - 24
      - 48
      - 60
      dropout: 0.3
      embed_dim: 96
      embedding_dim: 64
      heads:
      - 1
      - 2
      - 4
      - 4
      in_channels: 1
      out_channels: 1
      r:
      - 4
      - 2
      - 2
      - 1
    name: SlimUNETR
  train_mode: true
  work_dir: /data/jayeon/TrainedData/Paper/
train:
  loss:
    dice_loss:
      smooth_nr: 0
      smooth_dr: 1e-5
      to_onehot_y: false
      sigmoid: true
    focal_loss:
      to_onehot_y: false
  metrics:
    dice_metric:
      include_background: true
      reduction: mean_batch
      get_not_nans: false
    hd95_metric:
      percentile: 95
      include_background: true
      reduction: mean_batch
      get_not_nans: false
    iou_metric:
      include_background: true
      reduction: mean_batch
      get_not_nans: false
  optimizer:
    betas:
    - 0.9
    - 0.95
    lr: 0.002
    opt: adamw
    weight_decay: 0.05
  resume: null
  save_cycle: 200
  scheduler:
    max_epochs: 2000
    warmup_epochs: 5
