DiceMetric:
  include_background: true
  reduction: mean_batch
  get_not_nans: false
MeanIoU:
  include_background: true
  reduction: mean_batch
  get_not_nans: false
HausdorffDistanceMetric:
  percentile: 95
  include_background: true
  reduction: mean_batch
  get_not_nans: false