generation:
  direct_path: null
  epoch: best
  weight_path: train
inference:
  direct_path: null
  epoch: best
  weight_path: train
run:
  checkpoint: Pretrain_Test
  device_num:
  - 1
  genenration_mode: false
  inference_mode: false
  loader:
    dataset:
      bbox: bboxTr.json
      imageFolder: imagesTr
      labelFolder: labelsTr
      name: amos22
      root: /data/jayeon/Dataset/amos22/
      scale: origin
    generation:
      test: 1
    train:
      test: 1
    validation:
      test: 1
  model:
    args:
      blocks:
      - 1
      - 2
      - 3
      - 2
      channels:
      - 24
      - 48
      - 60
      dropout: 0.3
      embed_dim: 96
      embedding_dim: 1
      heads:
      - 1
      - 2
      - 4
      - 4
      in_channels: 1
      out_channels: 1
      r:
      - 4
      - 2
      - 2
      - 1
    name: SlimUNETR
  num_workers: 8
  train_mode: true
  work_dir: /data/jayeon/TrainedData/Paper/
train:
  batch: 4
  loss:
    dice_loss:
      smooth: 1e-6
    focal_loss:
      alpha: 1
      gamma: 2
      reduction: mean
  lr: 2e-3
  metrics:
    dice_metric:
      smooth: 1e-6
    hd95_metric:
      percentile: 95
    iou_metric:
      smooth: 1e-6
  optimizer:
    betas:
    - 0.9
    - 0.95
    lr: 0.002
    opt: adamw
    weight_decay: 0.05
  resume: null
  save_cycle: 200
  scheduler:
    max_epochs: 1000
    warmup_epochs: 5
